// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type Bookmark struct {
	BookmarkID int32
	UserID     pgtype.Int4
	PostID     pgtype.Int4
}

type Category struct {
	CategoryID  int32
	Name        string
	Description pgtype.Text
}

type Comment struct {
	CommentID    int32
	Content      string
	CreationDate pgtype.Timestamptz
	PostID       pgtype.Int4
	UserID       pgtype.Int4
}

type Event struct {
	EventID       int32
	Title         string
	Description   pgtype.Text
	EventDate     pgtype.Timestamptz
	MeetingPoint  string
	RouteID       pgtype.Int4
	CreatorUserID pgtype.Int4
}

type ForumModerationLog struct {
	LogID           int32
	Action          string
	ActionDate      pgtype.Timestamptz
	ModeratorUserID pgtype.Int4
	AffectedUserID  pgtype.Int4
	PostID          pgtype.Int4
	CommentID       pgtype.Int4
	Reason          pgtype.Text
}

type Notification struct {
	NotificationID int32
	UserID         pgtype.Int4
	Content        string
	CreationDate   pgtype.Timestamptz
	IsRead         pgtype.Bool
}

type Post struct {
	PostID          int32
	Title           string
	Content         string
	CreationDate    pgtype.Timestamptz
	UserID          pgtype.Int4
	IsSticky        pgtype.Bool
	IsLocked        pgtype.Bool
	PostCategoryID  pgtype.Int4
	AdditionalNotes pgtype.Text
}

type PrivateMessage struct {
	MessageID      int32
	Content        string
	SenderUserID   pgtype.Int4
	ReceiverUserID pgtype.Int4
	SentDate       pgtype.Timestamptz
	IsRead         pgtype.Bool
}

type Role struct {
	RoleID   int32
	RoleName string
}

type Route struct {
	RouteID       int32
	Name          string
	Description   pgtype.Text
	StartLocation string
	EndLocation   string
	Distance      pgtype.Float8
	ElevationGain pgtype.Int4
	RouteMapLink  pgtype.Text
	UserID        pgtype.Int4
}

type Rsvp struct {
	RsvpID     int32
	EventID    pgtype.Int4
	UserID     pgtype.Int4
	RsvpStatus string
	RsvpDate   pgtype.Timestamptz
}

type User struct {
	UserID           int32
	Username         string
	Email            string
	PasswordHash     string
	RegistrationDate pgtype.Timestamptz
	ProfilePicture   pgtype.Text
	Biography        pgtype.Text
	LastLoginDate    pgtype.Timestamptz
	IsActive         pgtype.Bool
	RoleID           pgtype.Int4
}

type UserSession struct {
	SessionID    pgtype.UUID
	UserID       pgtype.Int4
	CreationDate pgtype.Timestamptz
	ExpiryDate   pgtype.Timestamptz
	IpAddress    *netip.Addr
	UserAgent    pgtype.Text
}
